# Generated by Django 4.0 on 2021-12-30 17:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyst',
            fields=[
                ('first_name', models.CharField(max_length=25, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=80, verbose_name='Nazwisko')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('laboratory', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('1', 'Organic'), ('2', 'Non Organic'), ('3', 'Research and development'), ('4', 'Quality Control')], max_length=1, verbose_name='Laboratorium'), size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratory', models.CharField(max_length=100, verbose_name='Oddział')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('analyst_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notebook.analyst')),
                ('is_supervisor', models.BooleanField(default=True, verbose_name='Kierownik')),
            ],
            bases=('notebook.analyst',),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=254, verbose_name='Temat Analizy/Badania')),
                ('content', models.TextField(verbose_name='Notatki z przeprowadzonego eksperymentu')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='my_media')),
                ('date_sent', models.DateTimeField(auto_now_add=True, verbose_name='Data wysłania')),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('analyst_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.analyst', verbose_name='Analityk')),
            ],
        ),
    ]
