# Generated by Django 4.0 on 2021-12-30 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Laboratory',
        ),
    ]
