# Generated by Django 4.0 on 2022-01-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_delete_laboratory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='my_media/'),
        ),
    ]
